export const IPC = {
  loadState: 'state:load',
  addProject: 'projects:add',
  removeProject: 'projects:remove',
  installedLaunchers: 'launchers:installed',
  loadCatalogue: 'models:load',
  saveChoice: 'choices:save',
  listChats: 'chats:list',
  readUsage: 'usage:read',
  usageChanged: 'usage:changed',
  notify: 'notice:show',
  readAgenda: 'agenda:read',
  refreshAgenda: 'agenda:refresh',
  agendaChanged: 'agenda:changed',
  sendSnapshot: 'companion:snapshot',
  askCompanion: 'companion:ask',
  listConnections: 'connections:list',
  googleStatus: 'google:status',
  connectGoogle: 'google:connect',
  disconnectGoogle: 'google:disconnect',
  googleChanged: 'google:changed',
  theme: 'theme:get',
  setTheme: 'theme:set',
  themeChanged: 'theme:changed',
  withdrawNotice: 'notice:withdraw',
  setBadge: 'notice:count',
  openSession: 'notice:open',
  saveAttachment: 'attachments:save',
  gitStatus: 'git:status',
  createSession: 'session:create',
  closeSession: 'session:close',
  write: 'session:write',
  resize: 'session:resize',
  sessionData: 'session:data',
  sessionExit: 'session:exit',
  openExternal: 'shell:open-external',
  menuCommand: 'menu:command',
  report: 'log:report',
  reporting: 'log:reporting',
  problem: 'log:problem'
} as const

export const E2E_ARGUMENT = '--telegraph-e2e'
